/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 767110e0b510754ebb61e69f2ccdb9d7)
interface __BaseEnv_CloudflareBindings {
	KFIND_ASSETS: R2Bucket;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
