export const RoutePath = {
  Overview: '/',
  GettingStarted: '/guide/getting-started',
  Installation: '/guide/installation',
  Workflows: '/guide/workflows',
  Goals: '/guide/goals',
  Options: '/cli',
  QuerySyntax: '/cli/query-syntax',
  PartsOfSpeech: '/cli/parts-of-speech',
  Expansion: '/cli/expansion',
  Boundaries: '/cli/boundaries',
  Phrases: '/cli/phrases',
  InputOutput: '/cli/input-output',
  Diagnostics: '/cli/diagnostics',
  CliResources: '/cli/resources',
  Recipes: '/cli/recipes',
  Agents: '/agents',
  AgentWorkflow: '/agents/workflow',
  AgentSkills: '/agents/skills',
  AgentIntegrations: '/agents/integrations',
  AgentAutomation: '/agents/automation',
  AgentContract: '/agents/contract',
  Architecture: '/internals/architecture',
  Pipeline: '/internals/pipeline',
  QueryCompiler: '/internals/query-compiler',
  Matcher: '/internals/matcher',
  StructuralVerification: '/internals/structural-verification',
  InternalResources: '/internals/resources',
  UnicodeSpans: '/internals/unicode-spans',
  Optimization: '/internals/performance',
  Analysis: '/internals/morphology',
  MorphPartsOfSpeech: '/internals/morphology/parts-of-speech',
  Nominals: '/internals/morphology/nominals',
  Particles: '/internals/morphology/particles',
  Predicates: '/internals/morphology/predicates',
  Endings: '/internals/morphology/endings',
  Irregulars: '/internals/morphology/irregulars',
  Derivation: '/internals/morphology/derivation',
  Compounds: '/internals/morphology/compounds',
  Contractions: '/internals/morphology/contractions',
  Ambiguity: '/internals/morphology/ambiguity',
  Coverage: '/internals/morphology/coverage',
  Benchmarks: '/benchmarks',
  BenchmarkCurrent: '/benchmarks/current',
  BenchmarkMethodology: '/benchmarks/methodology',
  BenchmarkContract: '/benchmarks/contract',
  BenchmarkCanonical: '/benchmarks/canonical',
  BenchmarkQueryMatrix: '/benchmarks/query-matrix',
  BenchmarkRobustness: '/benchmarks/robustness',
  BenchmarkPerformance: '/benchmarks/performance',
  BenchmarkComparisons: '/benchmarks/comparisons',
  BenchmarkReproducibility: '/benchmarks/reproducibility',
  BenchmarkReports: '/benchmarks/reports',
  ReferenceCli: '/reference/cli',
  QueryLanguage: '/reference/query-language',
  PosTags: '/reference/pos-tags',
  Configuration: '/reference/configuration',
  UserLexicon: '/reference/user-lexicon',
  Jsonl: '/reference/jsonl',
  ExitCodes: '/reference/exit-codes',
  Errors: '/reference/errors',
  RustApi: '/reference/rust',
  JavaScriptApi: '/reference/javascript',
  ReferenceResources: '/reference/resources',
  RuleIds: '/reference/rule-ids',
  Glossary: '/reference/glossary',
  Licenses: '/reference/licenses',
  Playground: '/playground',
} as const;

export type RoutePath = (typeof RoutePath)[keyof typeof RoutePath];

export const documentRoutePaths: readonly RoutePath[] =
  Object.values(RoutePath);
