import type { DocumentGroupIndex } from './types';

import { RoutePath } from '../route-path';

import { localized, page } from './types';

export const cliGroup: DocumentGroupIndex = {
  labelKey: 'navigation.primary.cli',
  categories: [
    {
      label: localized('질의', 'QUERY'),
      pages: [
        page(
          RoutePath.Options,
          'CLI 개요',
          'CLI overview',
          '검색 계획을 구성하는 query, 확장, 품사, 경계와 입출력 옵션을 설명합니다.',
          'Understand the query, expansion, POS, boundary, and I/O options that form a search plan.',
          [
            ['query-plan', '기본 검색 계획', 'Default search plan'],
            ['expansion', '형태 확장', 'Morphological expansion'],
            ['boundary', '경계 정책', 'Boundary policy'],
            ['pos', '품사', 'Part of speech'],
            [
              'normalization-and-phrase',
              '정규화와 구 검색',
              'Normalization and phrases',
            ],
            ['input-and-output', '입력과 출력', 'Input and output'],
          ],
        ),
        page(
          RoutePath.QuerySyntax,
          '질의 문법',
          'Query syntax',
          'atom, 품사 태그, literal 인용과 escape 규칙을 형식 문법과 예제로 정의합니다.',
          'Define atoms, POS tags, literal quoting, and escaping with a grammar and examples.',
          [
            ['grammar', '형식 문법', 'Grammar'],
            ['atoms', 'atom과 태그', 'Atoms and tags'],
            ['quoting', '인용과 escape', 'Quoting and escaping'],
          ],
        ),
        page(
          RoutePath.PartsOfSpeech,
          '품사 지정',
          'Part-of-speech selection',
          '전역 품사, atom 태그와 자동 분석의 결합 및 충돌 규칙을 설명합니다.',
          'Combine global POS, atom tags, and automatic analysis without hiding conflicts.',
          [
            ['coarse-pos', 'coarse POS', 'Coarse POS'],
            ['selection-order', '선택 규칙', 'Selection rules'],
            ['ambiguity', '품사 중의성', 'POS ambiguity'],
          ],
        ),
        page(
          RoutePath.Expansion,
          '형태 확장',
          'Expansion modes',
          'literal, inflection과 derivation이 생성하는 후보 범위를 구분합니다.',
          'Separate the candidate sets generated by literal, inflection, and derivation modes.',
          [
            ['literal', 'literal', 'Literal'],
            ['inflection', 'inflection', 'Inflection'],
            ['derivation', 'derivation', 'Derivation'],
          ],
        ),
      ],
    },
    {
      label: localized('검색 조건', 'MATCHING'),
      pages: [
        page(
          RoutePath.Boundaries,
          '경계 정책',
          'Boundary policies',
          'smart, token과 any가 후보 span에 적용하는 구조·Unicode 조건을 정의합니다.',
          'Define the structural and Unicode constraints applied by smart, token, and any boundaries.',
          [
            ['smart', 'smart 경계', 'Smart boundary'],
            ['token', 'token 경계', 'Token boundary'],
            ['any', 'any 경계', 'Any boundary'],
          ],
        ),
        page(
          RoutePath.Phrases,
          '구 검색',
          'Phrase search',
          '여러 atom의 순서, line 범위, max gap과 span 결합 규칙을 설명합니다.',
          'Control atom order, line scope, max gap, and combined match spans.',
          [
            ['atom-order', 'atom 순서', 'Atom order'],
            ['gap', '간격', 'Gap'],
            ['phrase-span', '구 span', 'Phrase span'],
          ],
        ),
      ],
    },
    {
      label: localized('실행', 'EXECUTION'),
      pages: [
        page(
          RoutePath.InputOutput,
          '입력과 출력',
          'Input and output',
          '파일 순회, 인코딩, text·JSON Lines 출력과 pager 조건을 정리합니다.',
          'Specify file traversal, encoding, text and JSON Lines output, and pager behavior.',
          [
            ['input', '입력 source', 'Input sources'],
            ['encoding', '인코딩', 'Encoding'],
            ['output', '출력 형식', 'Output formats'],
            ['npm-cli', 'npm CLI', 'npm CLI'],
          ],
        ),
        page(
          RoutePath.Diagnostics,
          '진단과 오류',
          'Diagnostics and errors',
          'compile, resource, I/O 오류와 종료 코드를 자동화 관점에서 설명합니다.',
          'Interpret compile, resource, and I/O failures through stable exit behavior.',
          [
            ['diagnostics', '진단 형식', 'Diagnostic format'],
            ['error-classes', '오류 분류', 'Error classes'],
            ['exit-status', '종료 상태', 'Exit status'],
          ],
        ),
        page(
          RoutePath.CliResources,
          '사전과 resource',
          'Lexicons and resources',
          'embedded, full POS, enriched predicate, component와 사용자 사전의 역할을 구분합니다.',
          'Distinguish embedded, full-POS, enriched-predicate, component, and user resources.',
          [
            ['profiles', '사전 profile', 'Lexicon profiles'],
            ['resolution', 'resource 해석', 'Resource resolution'],
            ['validation', '호환성 검증', 'Compatibility validation'],
          ],
        ),
        page(
          RoutePath.Recipes,
          '검색 예시',
          'Recipes',
          '코드 탐색, 문서 감사와 에이전트 입력에 맞는 명령 조합을 제공합니다.',
          'Apply command combinations for code exploration, documentation audits, and agent input.',
          [
            ['code-search', '코드 검색', 'Code search'],
            ['document-audit', '문서 감사', 'Documentation audit'],
            ['agent-input', '에이전트 입력', 'Agent input'],
          ],
        ),
      ],
    },
  ],
};
